config:
    sensitive:
        NUXT_PUBLIC_APP_CAPTCHA_KEY: ENC[AES256_GCM,data:7TwPL+6L9rjw/YPDI2V0Nisknc3X+i+aylmq1JM6bONl7X/53x4akg==,iv:RYBef5MpOgS//OYTlLMY0urgUHF/dCFyRpUswWpVamA=,tag:29bDELCJiqeLPHqsTENllA==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:HzoFxKueJUZnfvoDr8o5o7m+KlfPrrzYNMF0LjL7qlw=,iv:DPkRKB3t49CHjPxY9k+brDlOqitSoi97aO1ZHaH/41k=,tag:FjldbeNCmAZkXS/x0s+7oQ==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:ruHJD8xePRoR77M0Up1YLHNxppm6l8c/ow==,iv:I1wr9eUNvUf9mD8Q4kfv3J+8Tsae6tFohkGPexp+M7c=,tag:deVqIVPDLGBDx4WrP0NxNw==,type:str]
        NUXT_PUBLIC_APP_MIXPANEL_PROJECT_TOKEN: ENC[AES256_GCM,data:20i1pJc/OuehjIf8Qld2cAJAXQ18r1kBOMMdvvulGTA=,iv:PNt4x3TG7u8Zo/Mnl2xq+W7hb5HGA9PaaK8Wjm6woWk=,tag:t2LYQLotHoS2rV8PrrLU7w==,type:str]
        NUXT_PUBLIC_APP_SENTRY_DSN: ENC[AES256_GCM,data:hFhqSpjGaWWV5UHK+/RiaAM+RgVWRSox5jyOC2ZBkwexIAFMreZz6NheVlN+ORKznIGXU1ULZM6nAg0zy2V/tDU=,iv:HbShxC0iwtEqEZ34/5UyS/j5iDn6IL1tjZ7xrr3mBcY=,tag:b2H5NbDf+THrI78tdIBd6w==,type:str]
        NUXT_APP_GEOCODING_API_KEY: ENC[AES256_GCM,data:H02XSJtBgYvVJNYtkGKz34qRRA2wgHnPnsKOhDQUG2cArDgCNgrc,iv:rzUEWFjEkwqOimRchLVZbFWNpuB2YbmUVPlt1tlQyAI=,tag:GqPDSzGSRliTOo9xVTVoWQ==,type:str]
        NUXT_APP_OPENAI_API_KEY: ENC[AES256_GCM,data:sSrmO7c3mWMdAuX9YCdj5y1J3txQ8H3rbZdRDYLcJadJXIOvlKh6UMqx3qEHxrmh/vSGBS7aVlEsLC9RFmE+qA3q3KQkbIjFgIktjUbi0DHYj+5Ru8QxE3/lbS69ZLayj29yHdEMsUGozryG5e9VZV89GnPYkAwr7WFZts2yd1o3BJjZi1FDnfnUFdJMo4mUnMCzfa+6N1mxsg9U6e9fgY+1uKk=,iv:d4XZrBFeqHvTmAevFpeHoYmNOEoZ6On97R1gTxIhkSg=,tag:XDp0LXcRl0ymm8yZEIYz8g==,type:str]
        NUXT_APP_SORBOBOT_API_TOKEN: ENC[AES256_GCM,data:T4nE4tTKo/IkAFdqG8neoNMbLJJnISR2FDt5kvPDYDpIslSFVLAWKlaTdTdy9J82q3uSGBJFTA6iPOSfH5Ht7rPv5ZFM7AZX4/pr/eM8tr4M8I6KMVmyZpwLs7vOq5jkG+eEt2L4AGbMO45sN3uvA9wQrMRfTcU7STOQ99djSDtFEZwK8bCNi4jic6OSYhcV3QP7R4gP123dQdSTrjSHPR/CA5PmQZ48YpFSjBJxR6KCwqiHsdiGUoDSnee7OcC1vsNm2k5s1+DGrjTcqHZjItAa6jFcPFUlkKHrS19F3U/rTqOLvH+gWRKFkHPgROF0o6ElVoG/QDTNW7F+x0WP52MMeh7hzhpyoa5dmsrWoM6IE+qnuYv0c5LJYnL+R+MYOu2z+r60z5xGHTGzyPCP/WZYjX7cdF6TOIRNYUZhzs8AaKFAQWSJaSghqmclGr35MMQ37ac8iN0bfmS1lRO/ucjIZPJGtMb6EZ8gJKh64a0tbhHJ0wZdY8ueNHbvJzONoDrcTP/SL7kmiSiDB4fK91+T5CunnkIUqzUIYAMROp+sBqcG8+da5CpdonK6K7Rm8jdhkg==,iv:ZZatTRyZtkUzW4UmyjJe5PVV+1xrRVkX+z0ZxG2l2oc=,tag:VJQCoogxNcHCGjmwveNl4g==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRllJUlpscnd0T1ZSWXhI
            dDY5cURxTzd5M2tiQWp4TytnWDNsN0dDSW1JClNzVnhSQ3NoMnFsbjJNNThNTC9U
            WWNHTDV4UWtIYlYxeGJCenFaMllraTgKLS0tIGdHc0w3Z0hmcitBcUUwYXh3NTdy
            eWZRcm9vK1JjOEh5RlpTT1R4ODlwOU0Km+wp+ud0H5JuAmY0WR/ch9rreeObEzzP
            9E/K4muTk81xQUIJwmVn6SAQrIHg/TcbJ4r6+AJmOhjW3xIIt72mpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOStBNWZ2dWhtcVlwblds
            SU51aEQwbVQ1RW81ZVlMRE9ZM3hKTnI1eXcwCkVJdlhpcm9YRlVUYnNiMG1VMEZG
            ZStuUmFqTlhJazNpeGx6V3dvVmJwR1UKLS0tIEZFVnRhTkpDZVcrVFJYNjNzNnBG
            NVQyMDM0QzVvN2ZjKzNEeVU5eDFZU2MKLOSgpi9DUT4AJNK4ki9w59JYXsJ9rPo4
            roebTIe3SX0l8r1+O9j1d4LoMJcaC+d3LC35KemvDR2nxlDVP2uMRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOWdYTnRwU3FZbWZHSzBo
            L3lHN25acy9xaTk1M1NvTE51OTZtZ3lxZ1VzCjFVdk40NzZrYjRWeVgxTm53VzBy
            djJEWEhRR2dsV1RiVXlMclc5RitWZEkKLS0tIHI3WVluTHYwVTVmK2ZVdnMyU09x
            MUlVT1AvRkNWeEtBMXFIeTIyYnZzc3cKjUt7JpokjjZS/jufChKvj6pw8BLYfzHD
            GEaUJtC8tcvDQWW1En3NL3theyIA+bybe7H7QdXySDvkB3WXw4r2xg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVDQ2N05zcUZMN1RTajI5
            TUJiT3oyZXBIcklGSit0OWdoNTVEQVRJRW0wCkJSd0FyVDZ3ZWxkZTc2aU4wZWRi
            TUwrbVlrbWgxQzBibWhYSE1zR1h3c3cKLS0tIE0zd0VYTmN3S2p4dWo3NkRFZ2dk
            VXIyWFl6ditKUDRSSFF0R1JhZ2NkbUUKO2Bj7fpkDVxMp+5Oe2iH2EtNYDinofaQ
            jUBPx1sHRXqMTHOnd0giZ1e0zsDnCTtkvWHmRMK22jHWmac/pKxwIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T14:23:20Z"
    mac: ENC[AES256_GCM,data:vmEkhy7DiWmGnFH2FueqYMQstKEQxCJXToSPIHo9geF00GC8vj0qy3PQaNhIJyWz79Xh/MInGWUMMVi6v3ayj4hwVk4qU9I4ET+KbukqgLdgm4WtLJvs/1+wuGtOWrd3CDh/SMffp/yq3ekjwvAY1O+AsHGndUkSzOSraG47N+0=,iv:z+jrwHHlX5TGF3Ch3iWzDvTddf6uRncLg16thHaeBXE=,tag:++s9hW3mY7Jj49aL6U38Tg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
