config:
    sensitive:
        NUXT_PUBLIC_APP_CAPTCHA_KEY: ENC[AES256_GCM,data:EJ8PD6Bb+nUN3vx0gz21I5PNEeasKOm17WDOdNkCgwZ3s9hoOTTj+Q==,iv:RKjAnkRULI4iZJYH52bcz97sFc6CvIkQ1a+aR7sd+Q0=,tag:rRF548v5xyw9NaBNi9kXmw==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:cuDLLmQo92fIX/VrvE67XSP3zusJfI6AUH1eG3t7An4=,iv:M6mAZPVtPEGTK2Q+F1l5Q2qfe0y1JkJiaaDUaMSLACg=,tag:CuVd1Yf6ZMsVu934nrvWhA==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:JOCTHKo1GqTipwQBn6Otjs5lHI5c,iv:wugi0qMqsOXq0BSbGM0qFZ6JgscUVPKOTUMWwQxkMm0=,tag:THLLP608/WDdAvOETkmYOA==,type:str]
        NUXT_PUBLIC_APP_MIXPANEL_PROJECT_TOKEN: ENC[AES256_GCM,data:T2uUOflyvcwxElnl6BwcK0CANYgrDfg3cFP1cwZxeIY=,iv:QjsK3106A3pAkKi9zTH7yFw9Sb02XoU93XqNclJ5s0g=,tag:myQ/K1i0USGlbXjwTiMuMQ==,type:str]
        NUXT_PUBLIC_APP_SENTRY_DSN: ENC[AES256_GCM,data:m1Tzz7jdqKGeUseyfh8SvMfpNX674XY0R1yrP+fgBipt4uUVdpywb/nIo0AoTVmxt0u7JO0+Lux7fXy5VVAsHDk=,iv:pb2mCOmgveNL3NH5VyVhaHOaZmH1QlP00nvbQMDEXqg=,tag:tDTkOFhfVexnkmdmr7ez0w==,type:str]
        NUXT_APP_GEOCODING_API_KEY: ENC[AES256_GCM,data:ygj1xkfUpNwzxUorVC+eHLXfgzL87Hh0LLlIaiuPl/8/OYR8dVdD,iv:al6lr3IzxzBPAj6DPLiYj539V+K9FIuAguGsX74ewmc=,tag:RJLyJ4bLcBucKftodxXTgw==,type:str]
        NUXT_APP_OPENAI_API_KEY: ENC[AES256_GCM,data:p1rqidtGJFRlVcYWbTEaZBe6EnTRmxLTgX8PFKC4l8KGPL0VnoKOLL+yNqumgSqlNyONGs6x0RFEY9InRWylcRm57X1QhCwE2X/n2P6W1uzE1pK0hFxcrOwF8vB/0W+wB4qwbQgXvXM/68/dM1c/wCrmSk0er1iWqR/oIG5C+u5w8TDNkKmz/TDs5KgrDDoj+4KC9uRb+VsoX77ho4lrRXmp/bY=,iv:tTX+OmuDkTAfNxZOukA4vvSpb0mvxwzmNlFmD9OSN8Y=,tag:AfQ0gPJqPlLOIkLtu4hDyQ==,type:str]
        NUXT_APP_SORBOBOT_API_TOKEN: ENC[AES256_GCM,data:ZAnA6WOEBZBSsh1t8bLHtL6qXnUscz/kwhSOMJyeKPvOsT0tV5D8TRF/aRqNRTOiQaHUI7FN/mmIh5LicZrur5Tr0/Q4LghnR2FnWa8J3UH5PkbrFZPeeh4DHtgTcN9j+1f3hCGgHWe7cNy9rBJIX/HUGBs6uNE6Lv4Nf4riLfCJldOUk4pYESu4TwCcaExXNwuKkXsciXkAVG2b2qMLo0eWZ68jGz4CevtR5WkbCjKH9JkyOhlrJdJTrUFLgTpYNmxT9HLAWMk51PqiFHTrI1aOdCKwxx3btYIbtQAasYm6n+p+54u2V46GNfzRWwwaDVEYYYVDO1rNi1vHEv2IIO7PPmFJO0biuAB7tWvlOPlI/9KdVv7H7BhWB7ziscDUaLVzbMI66yIHeBdYIvcJTG3qQ1opqlkLajEh7YhtT0USejNHj8+c3brZCKsjEk5Clbk4br5bUAkkOndwYS8PtbHi6GuRrCsvDNGaH+EEmztF1ljhfVMn2S4N3xzkxCpKapQTzPIG0GzmhTEBjeBKOLioizAfKXG/phdtyrHjNeqRjINcFmJekJJEzink1SVNe9PTHw==,iv:2H7uHSVC5Ke13NXazCHxLsi/GlAVdvlVkVFEfTC84SI=,tag:zrNgDnPbd07uPDtZJsvD8g==,type:str]
e2eEnv:
    sensitive:
        USER_ADMIN_PASSWORD: ENC[AES256_GCM,data:RXWsMLtLB8v5YSWB,iv:tK9wwRpTuXdSFy5jyjk5aQvXAI58MZiu+aqVXHiz+3Q=,tag:LWyz8EF5wivXiw7BnWz+Fg==,type:str]
        PLAYWRIGHT_TEST_PASSWORD: ENC[AES256_GCM,data:GjkRgTf5NKp6iJy6,iv:cVhuJZRbTnny6IH9gMLQCAnkY1F8ajOUlu/jU238YkA=,tag:qSvPNo88SauKUfzBa4R/tw==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZzE4V283MzNjRm1HQ1pj
            Q05vSVFna0dPMXZGZW5Xb2VONDJvUTl5UXhJCnFlWEtuN0tQOVFyS1dsY2VpN1NI
            ZjRLdk9DOFVreGlCTEoxK0E3VzBXVlUKLS0tIHhYN29ROWlGNWJibnNPNCtmbi9w
            VEkwNkp2bDlnamFkZ01GTUpyWmhtQzQKtabrQpP+eDrH6Fas4yMZ88NZFooCG0+J
            lMOpti2qkNb4nhP5UdN0fjo3wD3hPEoHD/+/XAp1aH3m2KSzsf9rkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVWVKYnJPVURGa1ZFQWxK
            dHpIQk91SFE3dnYybnFmOU5KQ0dYL0N3WXgwCkJPVm1vcXpUU1Z3b2VqK0wyaXlj
            UHIwSnd4YVlTK1BkeWxWaDR5Y0RMaVUKLS0tICthVFo4SWZCaHdFZTVEUkZJbjE3
            VzZFM3ppc283WmV4WVJTeGo4ZVlMWjgKTmNFW9P5RJ4pzhI7NE4NSJrdodxKjyDS
            fH0kji+zlPuWo5XfMcxZQVUf6w5BzOwo1w072NOjerFep5/Z+xjWMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNkpVRVgvMFh4ckMyZUhj
            OHJnSkdrZ3NtTUk2bThKZGJnN2RmYTd6anhnCnp3eWI1c2xFNjBHUmlhWDdtMUNH
            bDBaQmdRVmhqUGc5MkNQaVRUOVRNNjQKLS0tIFd0bXpmRXY3ZVFHMkIya09JNnJ4
            UFVDOTRmTVZBOHViUWc1cWd2cFkzd3MK62o9d2lOAxFW3EejYVZ7v6JPuYrG9ELF
            tPD4dPulq10MPCESkJR4eM6iKFDzVUTccMnJjriTmFClTFtOLn5YjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCY2RMUmxxNzcrYnVTYTFJ
            TDQveXFNOENCWHAzc0JpV1FNSjN1NDAwMjBBCnhDMVQ3YXJCcFpEZWtRNk1GTCtR
            MWNkUk95N09VaC9PMmIwS0hUZEdsQTAKLS0tIG5ua1VsS2QvTUlaYzFOcDZRUzM0
            ckMwQm5qR3Q4QzdxajhpWWR6R3RzU1kKBYbH4CW+3sBMRr8m2JhommIJEWy06HGM
            BXIcaW153uhNaxcQDpplJBxhsqShk9l0gVWMeTppiVfmBNIjtHZiqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeTYycFQ3R09WLzdhMFla
            Y0ZsbHBaNHhiZlZGb0p4ajZtSWY5RmlMTXhzCjdPT045cFJXR1J3VVhreGxUczhq
            TDJ0dHo5UjVsMm9oQVEyT1QrZ1dmejAKLS0tIFVmZXFpOUQwelUyODVlaDg3K29B
            anRsc1dGVmF3ZkROTm9WSVdkR3NSTzgKEKW3xB9MHRDg5/nGX1ihL75S+eicwTWH
            Slph/INQfLVAF33/MoGrEQesGFF9lw0ee2ygFeEWpCgBaBuikFRB1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOG40ZURwY2JTYW5PZWph
            QXkwcUltWHNTQ2tnRk1DS2hZMFk0ejhUT0NZCkgxaUZ0by9SbVphYUtFZUFNRkxk
            ZFF6VndtdkdjMURIODluZDgyVEdiSDQKLS0tIDZMZVlyWkN1Q1NsT0xjbDVvV3FM
            TzlvWlRNR3VEdXl2RzY1SFNPUHJYTkkKpzDz8XRxIbFWVwZvVnWC1VnlFI4B3j2U
            ANAiHtLHd4Ou+4xWgMdWUfJ8z9ORhKIbj9Bk1Irwjv8uC4lM6824Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T14:23:55Z"
    mac: ENC[AES256_GCM,data:ZTL0QidGEPVK85YFT60ZSjWNXQuFzWZd9q8bxGjZSkljKuEb6PNaiBhNByoHYe8FKNodNs8hbYGJThMTxPtI8LStIrBzLfpMLJCT/kEJLYDeKLrIrRUF8jGmDqJ4Fzj4PJKA9wa+M8s3vKF1GWG6/R49Tuo6LDOHHliKiKVuatg=,iv:wVCKmO3lNqhvcOaFy4V2Nk0LL2m1Sz5Vk2ZIwryMLFk=,tag:3o7VrWUasuqi1QU+u+9Ofw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
