config:
    sensitive:
        NUXT_PUBLIC_APP_CAPTCHA_KEY: ENC[AES256_GCM,data:9leXWrej0l0kvbutlvjWVlJwplIPASs6nJjlOJ7G28j+MRWidTTYZQ==,iv:Wqx9qBrnggiF3Is/3hYnc0bm2rOpPOItoFwqsQuMfo8=,tag:Aixd7krO1kM+ms4QvCKf/g==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:ApTw7zBin95Wi7IgjVYpp6ni5UpvanOQrXil8MfJG0Wojfk7,iv:q8INQ6aex8GTIH/hvtTLTSt3AA6J3Gi6ZEvZvtnti7Y=,tag:6mL2+ru8OKAOUh6eihNYTQ==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:FLK9uUbcT6ySg+oD9l4N+2BZ1rxBdVWPlAhMsQ==,iv:zptAj7xf7McJS3PSQ928+Lyg7vBAv8mTziZiLZpNuKw=,tag:PhhTPliCWtmu64D1FDsweg==,type:str]
        NUXT_PUBLIC_APP_MIXPANEL_PROJECT_TOKEN: ENC[AES256_GCM,data:fqSqXC07qK66VsmmsAL8eoDEOY6wBuaDPVDUbiOyIjo=,iv:JDiFIYysTgJGl0hxVJCL0j29KnRUcJcjyf5QRraBp6Q=,tag:feDkrYZmvqsCXv2sCHtTBw==,type:str]
        NUXT_PUBLIC_APP_SENTRY_DSN: ENC[AES256_GCM,data:JGa7w9OE2CbuSyDR1+U3nILgkcjR4ry9YHTgbaj7O9/xRyixkMywd7WLiXpyQHIMqSpTFf1aWikiuJq6E8TRTw8=,iv:lLuYJoq1jpxqLiMVhKKAA20b8XAundiORB9eW1pvY4U=,tag:R5a/zWodxvEGe/fdSgnRZg==,type:str]
        NUXT_APP_GEOCODING_API_KEY: ENC[AES256_GCM,data:MakhFOnut32zPApPK+WgB7zMSasq9HCvIkb8Vw8I/NTqmOl5J4jh,iv:XzBcn7W2W/ej2GJeVv4idVkF/r30fCbeVJLoW9j9fuU=,tag:ZGWaxBD9EVR+F4zgtuJJHQ==,type:str]
        NUXT_APP_OPENAI_API_KEY: ENC[AES256_GCM,data:GA/QJ5DjzLswTDvM+XM/NRcQJQm2k4qrO4//aTWB/74EXLNE+41rimesWOmgEs0NSxHKJD0UUszGoescypE8VDMtwNddHR6evvaRr2grXjD/FpHIHsAv3/E0QgdTpmkNlAqgcMS4OUQlgyYH/ESoAEiG/CZrlE8aAE4iK/qBz/QOuPRmym2MHeaZTxI4jiyuj0KUJDtXQrQGvutI7JRUNiKTiwQ=,iv:R4elVuX/TkeceFeO5JF+1PuB4FRW9Gr03LoNueOswew=,tag:Ht/3gkHXcftLP8THm2Pa1A==,type:str]
        NUXT_APP_SORBOBOT_API_TOKEN: ENC[AES256_GCM,data:+57Y2hQSsm4Z1RzjGMAgl4DeAWfqmz8b4iBxQx4J/Cj0Pjj42aTkLDAtq/gqRS5BYIQYQ5BYLnovZSCCZuxUiyHzOocMZY8+1e//umAlbYUnEW5Nb8HRz1ogO1zyPP2RV5wU5HyCVlg3HKtZbu+0g7aPerRGUFdH/Wum14KnvWWQY+zrjbdC4ZEAYkyheulaRWR5Q6Wxf1zAbVADF5NfgUF+OOSKDF+xgWYt7yLEQMZwdKZguvbM72IV0oFd14K5x4c+pn3589GcScg8UA9RwIn3glRkGv+4K2Kp/3fHjt/ueP9RGprGB9C/laP+MiDGw11meta9lHaHZbL/7rw6bP84u6B+ZmxX7+8nnjxFXH45Yo7YNzql6wNL9ho8dUAZ4hn59O6mC3ZFx8cd+d01lC4gl2IjfZPhhPcDZ7a9GRTsoXXME9Pid9/JP5lOB8NEfri29sMF8RqAqjSlOOVTvhnMyNc9A1J3O120/JxNhEmpYGtoCceIutDR05qBnj/U3LW93Y35ImUozKWFK1GfpBzzDH8y+bxw7lf9DVOxSc3u8tguow5u47KAcxKCw6f6PLpJjQ==,iv:Lgx5/GREdHTAhWD1nzVgraMWMKF1RbeCmSwQ+SZzKBs=,tag:RUqI0zJ9VOqJ7Orc0n9o1g==,type:str]
sops:
    age:
        - recipient: age13da407hamk8c3rdp3nu3q8hqgxsefn902vrxsuphw2ljfmd2k5qqy7mgzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYmg1YlkvQ2d1OGtVdHBO
            TUlwWjBlNDNDM0JDUmZ2V0NucmY5MkY5NkFNCnB4U1ZDdFhQWGRXdjhmVzg2dE0z
            N2hYQWg2LzNKUHExZ2VPZDdJcTN1WVkKLS0tIEIwSGdQb1REbUtiazBXSTdZOEsx
            S2NUWGorK3UwbnljcUsyNVFzZHF0U1kKHOx9thzTFfAi1mBt6T6Ou7ICkaWmdBY1
            IidFx1EvVynlqbCmMOr6BJxB3WasVOcvKT4BSwBkXU4NvuzwJYJRyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NXJkRkpyM0hNTWJlVkk1
            cWxMQzdXb0ZzMkxlS1JWOEJLYkJYR2RjWVYwCkJxZUdLU2RlVWoxNTFaVU16MFEx
            VG15OVJRQ1JUOWtXRm04b3FIaytvUm8KLS0tIDBHYXNBc1lXUVNnb2RQRDl6a0Ev
            M1NsbkJmRHJBaHEzU2lqZk1RTVlyNjAK//JAokN9zUenDf6HMeBbiFiwKQVnjqgA
            dpcASL+AgnZ3dyZjtrq0p7RW8jgpALlh1RtMfQBpxWH/j6JecQgO6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdG1FSDJHUEluT05SMURo
            Y0h0Ynh1Rk9zeWNKZFJGZWFXMTAyZEpDdVNZCnk4NnN2VW1BNkxqT2puamhqSGJa
            bmpXbFd1WFpqSkpzRy9JM2NZRFM4NDQKLS0tIFNqc0MwRTJ1Z2wyYkRrT3RHclhF
            cWtnK2dUalhPcVUyYm1GOVZtSi9uc28KL14jYL/K6aya+83lExaD/5pRLBlxIPCb
            2Z/qpkPaPrfW0C0dEgP9mjUG1HjzUs4GhUtq43icCw6b9GhDTozBjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUWNZVE81ZWZXUlFLWnVJ
            ZnQrK2ZmWHdLd3RveGYySS85dllwTmY3QmpVCmtlaFhDOHk5ZCtSQXZab3JKUG1Q
            R0w0WlVCckFsV2lVcDlXYjJ2c2I0bFkKLS0tIEFxT2JLcm1YTThpa2VOa2xMZ1NE
            Q1B3ZG1sRGxtMjhGcUd0eVhFdjZKNFkKCPd6rHFD8/VvNQEMqdR1EhO4itOSe0xk
            1XBD96ymDEvsUY56A5rznQhgBorBEaPdhucg4WkLMVOLdF9AxN8jUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMM3Raazl1T1pPQmYxcUZU
            TitsaXhHMkFtS2lYMG1ocnJDajNxTVcyRmljCnNCZE9pSXBmcnNFaE16anBNUFJa
            ZDIwTXZDTmNkQlRmOHVZcWlrSHo4dVEKLS0tIEdmM29SLzJ0elhRbWJWQ1dnbW0y
            cGFsUWVzWmFNWUwrL1Jadlh2c3JmSzAKAkELxkP420IdW5KhTdyHmSL5J1GZ67xy
            xRXwqQbLQUOyNvNYrrjBBtBxBTQvwjySNZIxGTdcmoQOVxRvD1M3VA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaC9UV1VDZjhGSGdWZEFB
            RWxMUDA4RWxISTJGRTYzVXc5YUlGVmlxM3dzCi9xMHEvNUhEODYxS0xHWmNZTktu
            VFNSK2xnQWJPRFA1dk5MZWpocmdSVDAKLS0tIDlCWTZhN2lEWTVFS2dxbXE0U0pB
            VlA1bGttdjZDOUtvcUg5dEJuZXdPdjgKTsDgD9UfFIEfxgC3WqgEH4mujSkVVqL3
            0w4cQ+OmOkcx0E/qT4RukCJ//+8w/et0+eVSgoxMCsVt73wG++hnWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T14:18:17Z"
    mac: ENC[AES256_GCM,data:pSHJnjahARvYTn+hAyMjSQoeTT9KoeNyZPxvmOYVA9LHn+B+jM3lvKrJOfR14G0NgPctApEv1YwE6mKYOoFDOHnbnrwdUtZQ6FybHtUiLW9kVTIPOjGvuufASEsehi9iLPBZ3ow/q/2z3Fn+4g7k8QpGxUrrN57QC3o9OvNSOwE=,iv:6tldFiHH8iiuPbxjJm4uXO8ho/fjyf2d1vGgWaRPyV4=,tag:ikS+IXGkbwUSPStyGzEMpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
