config:
    sensitive:
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:qvpjhCxqS0TCcFm4IaQkyug=,iv:B8e1dF2k6qPp7gtVvOQCntLyZkvhS5P9+OVIrWXVxd4=,tag:GHDlinTXJpYCMyD2t8DCHw==,type:str]
        NUXT_PUBLIC_APP_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:STOHqM1ibA19wuLny/F9TVA702ZBDkd3ze7k1ma37aQ=,iv:NepUs++jJ0E9XE/iSEfK0gkub5sbvE0kD6zDs1TMXYU=,tag:bFrvWcFqfisbsYLllEMqEw==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUnNJREQ1bkhmaFBZYTlU
            cXltbGpoNmpNeWFuaDdzNUlKOFQ3N1dHUjMwClZmSE9lSTFkTkN6bmVmS1YvYTI5
            TExiMll5bWp1RUZQcEkvazNzSWRLUlUKLS0tIEF3ZTZkbUN2TmFUYkw5dTI2eDJS
            WnpEMzRHekZLMjg3MS9UazI4YlE2em8K9DLgY61Gnu/bnbFWKvVXRFuOFkApPTe1
            QpSNkqAN03kH9+YoBnlIqqVWSvkFePhkEsltDVivd7Tl+vxaWjGV0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MG1wRkppQzdQWk1jWGhJ
            VUdqMldoTGlvdEwrTktjMlhmUVkwclBkZVIwCk1QTGlJWUlpeWNDV2ZLMjQ3U0E3
            UWx5ZTd6cXR3eE52R25tdVc2dHJId00KLS0tIFhocG9aNVd0MFoxdy81L1V3aTEz
            Q0djU0N2aGdoeTV3ZTN5WGs0UGd6akEKabs/BcMBD1dPeWtS/Ksx9W3al6r/C6xH
            6AE7kVH5R3aSwT7xWa7KHlMPlpOuB/PrcSJ165rGYpsHUfN25heXCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbGZuY3poVjJ1cWtid3g2
            enJLUmI3eWpqMnJmbW5yU2svYnpIV290a0M4CjlUUmdabTB4Slc1T2dJMzVkRkVq
            c0gxTDJValpjb3pxZ3cxTng3cUswYXcKLS0tIDBMTUxETkhkMi9ER3BYdTRRZ3RK
            dU9BNzdtbFNNUkFGU3Y5RGdtcDlVSFUKVDzBhaulw856FTnUiFfN1rPHzwcRWS56
            YABjXd4utBYJys1GV9dQs0T1g5mEDbxshu8VAZnH8kDnR9TiKecWrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cEswa3ZiZG5PWFpiRWpm
            UUxFUlZ5cEJoRDEzaVBGOG1HbEh4L0lkdkE4CllQZEtMTkw0VTYwRTd2YU9Pblp4
            N2FQQzFyK1BVYmJGWi9KNUoxYjhoNHcKLS0tIHBKRkk3T3VPOFRDZ1hPSEl0SHlx
            VER6T2hLL01sejN4bEFQUE9OMFJoaE0K9CjEGBPZNC/Nn9BXTKQRm3in536pQc1Z
            IhQQKHYXTu76uS6fP7/bqsRQVKjOddhWWUBk3JYFV3uh6O6rN5hiTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxenEzcUlnOWg2NXd4Y0lI
            bk5BWFF3K0ZvRzFybFlVNU5ld1hadjJ6U2tjCnQ1bHNkMGZZMll3MkloOWM4Z0pG
            OXp3eE43WVlOZnhHRGFYWmtWU1pxRVEKLS0tIFhBRVdJSDJuQmpHMENQOHJMODdV
            WlFvb0EzVE9EMHphNUN0SWp2MUpsQUkKvSsC/cuZ2nTiVFxqfTpJrV+/bAJ0ucU8
            Sp7osA/jZbNt9yBDGQ3nqIZoXqRLI3bEcPBPxtICHuACtA6CDL/J9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrelRUWGdqeG0yem5VU2hN
            cS9OZm9aUk1Ib1lJUDY0RGtzMmw1STI3Um1RCkgrMWR0T2FVSE4rU0RjbjRWYUky
            MWg1c2NBMEgxRzJaL1dQcENUM01XRTQKLS0tIE1DNVlNc1h6WUJKMFh5RFkyWXk4
            M2ZCR2FtU1VNNW9XTFphb2s0T3VYd0UKVyiXE986+n9KToB1ixwcljCIu+LPWJIs
            7hb6H79o93yXUC7bEPJXQZ7zYKxQgSsgvpnbu/mjgrWwM1k7XwgLjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T14:07:32Z"
    mac: ENC[AES256_GCM,data:x61Cy3pUlilfbWC9z1/wyBqpdpYg1kl/9Adn98XazodukmRTfl+YHW/Dj1HtBw8R3B+TZXkXzYTxvTicB4vCL983F+rPCOFG5mBuB+lTYK+IWX6ihzAq0v6G7vFTRzwwlFvOg8cg7q9/8Hx+mhpw08eB8lfzmYmmYhB+QB46aCc=,iv:tUbis/N8HQQx1QidZigm90DD3tvWOPExJSlcjfQTTRQ=,tag:N/CdziFHFRPcJLd04Up8Ug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
